services:
  alpha-hub:
    image: funasr-2pass:v0.3.0-20260811
    deploy:
      # 调整副本数为1
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: '4G'
    # 直接暴露端口（主机端口:容器端口），替代原expose和nginx转发
    ports:
      - "8000:8000"
    environment:
      - listen_port=8000
    volumes:
      []
